## Example 1

### displaing simple scaling with Sandard scaling and Logistic Regression, classifier

In [ ]:
from sklearn.pipeline import Pipeline

# feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
steps = [("standard_scaler", StandardScaler()),
         ("classifier", LogisticRegression())]

steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [ ]:
pipe = Pipeline(steps)

pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
# visualize Pipeline
from sklearn import set_config
set_config(display = 'diagram')

pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
# creating a dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 1000)

In [ ]:
X.shape

(1000, 20)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.33, random_state = 42)

In [ ]:
X_train

array([[ 0.15392202, -0.50977034, -0.32253916, ...,  0.38151086,
         0.87228253, -0.02487632],
       [-1.24099258,  0.9655992 , -1.10157839, ..., -1.17703548,
         0.71505409,  0.74497942],
       [-0.26976238, -0.36357157,  0.34692071, ...,  0.43616043,
        -0.8108026 , -0.78229337],
       ...,
       [ 0.83218886,  0.05692969, -1.11750528, ...,  0.79809555,
         0.31853669, -0.5954207 ],
       [-1.95729734,  0.8942782 , -0.98807701, ..., -0.03150816,
         0.61600665, -0.13472287],
       [-0.73138402,  0.33227748, -0.25853581, ...,  0.85533955,
         1.26443165, -0.38791269]])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
y_pred = pipe.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,

## Example 2

### Displaying a pipeline with StandardScaler, dimentionality reduction and estimator

In [ ]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [ ]:
steps = [("scaling", StandardScaler()),
         ("PCA", PCA(n_components = 3)),
         ("SVC", SVC())]

In [ ]:
pipe = Pipeline(steps)
pipe

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [ ]:
pipe['scaling'].fit_transform(X_train)

array([[ 0.15192436, -0.49515313, -0.34869046, ...,  0.38021891,
         0.85998312, -0.0281348 ],
       [-1.2618138 ,  1.02094487, -1.12148602, ..., -1.12391296,
         0.69886874,  0.76813248],
       [-0.27747741, -0.34491846,  0.31540398, ...,  0.43296047,
        -0.8646999 , -0.81153665],
       ...,
       [ 0.83934403,  0.08719099, -1.13728527, ...,  0.78225913,
         0.2925513 , -0.61825291],
       [-1.98778468,  0.94765501, -1.00889431, ..., -0.01838013,
         0.59737331, -0.14174987],
       [-0.74532836,  0.37013993, -0.28520008, ...,  0.83750453,
         1.26182431, -0.40362591]])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [ ]:
pipe.predict(X_test)

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

## Example 3

### Complex examples of columns transformer

#### Numerical processing Pipeline

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
numeric_processor = Pipeline(
    steps = [("imputation_mean", SimpleImputer(missing_values = np.nan, strategy = "mean")),
             ("scaler", StandardScaler())]
)

numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

#### Categorical processing Pipeline

In [ ]:
from sklearn.preprocessing import OneHotEncoder

categorical_processor = Pipeline(
    steps = [("imputation_constant", SimpleImputer(fill_value = "missing", strategy = "constant")),
             ("onehot", OneHotEncoder(handle_unknown = "ignore"))]
)
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

#### Combine processing techniques

In [ ]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    [("categorical", categorical_processor,["gender", "City"]),
     ("numerical", numeric_processor, ["age", "height"])]
)
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [ ]:
from sklearn.pipeline import make_pipeline

In [ ]:
pipe = make_pipeline(preprocessor, LogisticRegression())

pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])

## Example 4

### Hyperparameter Tuning In Pipelining Machine Learning

In [ ]:
import numpy as np

from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import GridSearchCV

In [ ]:
import seaborn as sns

df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
X = df.iloc[:, 1:]
y = df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
numeric_preprocessor = Pipeline(
    steps =[
        ("imputation_mean", SimpleImputer(missing_values = np.nan, strategy = "mean")),
        ("scaler", StandardScaler())
    ]
)
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
categorical_preprocessor = Pipeline(
    steps = [
      ("imputation_constant", SimpleImputer(fill_value = "missing", strategy = "constant")),
      ("onehot", OneHotEncoder(handle_unknown = "ignore"))
    ]
)
categorical_preprocessor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
preprocessor = ColumnTransformer(
    [("categorical", categorical_preprocessor, ['sex', 'smoker', 'day', 'time']),
     ("numerical", numeric_preprocessor, ['tip', 'size'])]
)
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['sex', 'smoker', 'day', 'time']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['tip', 'size'])])

In [ ]:
pipe = Pipeline(
    steps = [("preprocessor", preprocessor), ("regressor", RandomForestRegressor())]
)
pipe

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size'])])),
                ('regressor', RandomForestRegressor())])

In [ ]:
from sklearn import set_config
set_config(display = 'diagram')

pipe

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size'])])),
                ('regressor', RandomForestRegressor())])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size'])])),
                ('regressor', RandomForestRegressor())])

In [ ]:
pipe.predict(X_test)

array([11.6099    , 39.044     , 35.8606    , 17.98826667, 20.8962    ,
       40.364     , 11.94906667, 25.5377    , 21.0249    ,  6.84944   ,
       18.09923333, 35.94036   , 20.3359    , 14.84483333, 21.397     ,
       11.7279    , 25.668     , 20.4041    , 27.1408    , 20.8323    ,
       32.9749    , 11.7279    , 25.1248    , 23.0146    , 16.4003    ,
       19.0919    , 20.8255    , 20.0148    , 43.4422    , 11.0739    ,
       14.68528357, 20.16403095, 22.77      , 20.0661    , 11.05448667,
       19.3951    , 28.6425    , 13.77349095, 14.25101333, 31.8662    ,
       14.81183333, 34.002     , 19.8004    , 36.35      , 19.90655   ,
       36.4403    , 33.376     , 21.34463333, 21.70248095])

In [ ]:
import warnings
warnings.filterwarnings('ignore')

##### Hyperparameter Tuning

In [ ]:
param_grid = {
    "regressor__n_estimators" : [200, 500],
    "regressor__max_features" : ['auto', 'sqrt', 'log2'],
    "regressor__max_depth" : [4, 5, 6, 7, 8]
}

In [ ]:
grid_search = GridSearchCV(pipe, param_grid = param_grid, n_jobs = 1)
grid_search

GridSearchCV(estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('categorical',
                                                                         Pipeline(steps=[('imputation_constant',
                                                                                          SimpleImputer(fill_value='missing',
                                                                                                        strategy='constant')),
                                                                                         ('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['sex',
                                                                          'smoker',
                                                                          'day',
                                                                          'time']),
                                                                        ('numerical',
                                                                         Pipeline(steps=[('imputation_mean',
                                                                                          SimpleImputer()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['tip',
                                                                          'size'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=1,
             param_grid={'regressor__max_depth': [4, 5, 6, 7, 8],
                         'regressor__max_features': ['auto', 'sqrt', 'log2'],
                         'regressor__n_estimators': [200, 500]})

In [ ]:
grid_search.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('categorical',
                                                                         Pipeline(steps=[('imputation_constant',
                                                                                          SimpleImputer(fill_value='missing',
                                                                                                        strategy='constant')),
                                                                                         ('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['sex',
                                                                          'smoker',
                                                                          'day',
                                                                          'time']),
                                                                        ('numerical',
                                                                         Pipeline(steps=[('imputation_mean',
                                                                                          SimpleImputer()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['tip',
                                                                          'size'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=1,
             param_grid={'regressor__max_depth': [4, 5, 6, 7, 8],
                         'regressor__max_features': ['auto', 'sqrt', 'log2'],
                         'regressor__n_estimators': [200, 500]})

In [ ]:
grid_search.predict(X_test)

array([14.48165161, 30.34342411, 30.94653763, 18.71052834, 20.52693223,
       32.18762955, 16.88494071, 23.14783753, 19.39450729, 13.30473617,
       17.21845213, 27.97850329, 22.68886163, 18.57239529, 21.68086368,
       12.86910307, 21.3946865 , 18.32831562, 25.30984863, 19.08141655,
       31.00797031, 12.86910307, 24.48429423, 23.29640954, 16.79499212,
       17.96212241, 18.69518158, 20.66963886, 37.46618184, 16.97915268,
       15.54542893, 19.4323053 , 22.3724201 , 20.99702569, 12.42983083,
       18.31513336, 27.82826319, 15.59394634, 15.04339097, 29.79383333,
       15.00688188, 29.62183052, 17.9730598 , 32.57942737, 20.68651945,
       31.95244886, 30.94433447, 19.08626914, 21.44761764])